#############################################################################
# Makefile for building: libmeegotouchcp-socamfs.so
# Generated by qmake (2.01a) (Qt 4.8.3) on: Tue Oct 8 13:24:12 2013
# Project:  meegotouchcp-socamfs.pro
# Template: lib
# Command: /usr/lib/qt4/bin/qmake -o Makefile meegotouchcp-socamfs.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DMEEGO -DPREFIX=\""/usr"\" -DTHEMEDIR=\""/usr/share/themes/base/meegotouch/duicontrolpanel"\" -DCSSDIR=\""/usr/share/themes/base/meegotouch/duicontrolpanel/style/"\" -DAPPLET_LIBS=\""/usr/lib/duicontrolpanel/applets"\" -DDESKTOP_DIR=\""/usr/share/duicontrolpanel/desktops"\" -DDESKTOP_DIR2=\""/usr/lib/duicontrolpanel"\" -DDCP_UIDESC_DIR=\""/usr/share/duicontrolpanel/uidescriptions"\" -DTRANSLATIONS_DIR=\""/usr/share/l10n/meegotouch"\" -DMOSTUSEDCOUNTER_GCONFKEY=\""/apps/duicontrolpanel/usagecount"\" -DDCP_CATEGORY_DIR=\""/usr/share/duicontrolpanel/categories"\" -DDCP_CONFIG_PATH=\"/etc/duicontrolpanel.conf\" -DM_LIBRARY_NAME=\"lib${QMAKE_TARGET}\" -DQT_SHARED
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtSystemInfo -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I/usr/include/socam/socamfs -I/usr/include/qmsystem2 -I.moc -I/usr/include/duicontrolpanel -I/usr/include -I/usr/include/QtMobility -I/usr/include/meegotouch
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl/usr/lib -shared
LIBS          = $(SUBLIBS)  -L/usr/lib -lSocamOSApi -lqmsystem2 -lQtDBus -lQtGui -lQtCore -lpthread -ltimed -lduicontrolpanel -L/usr/lib -lQtSystemInfo -lmeegotouchcore 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .objects/

####### Files

SOURCES       = src/debug.cpp \
		src/logowidget.cpp \
		src/socamfsbusinesslogic.cpp \
		src/socamfsapplet.cpp \
		src/socamfswidget.cpp .moc/moc_logowidget.cpp \
		.moc/moc_socamfsbusinesslogic.cpp \
		.moc/moc_socamfsapplet.cpp \
		.moc/moc_socamfswidget.cpp
OBJECTS       = .objects/debug.o \
		.objects/logowidget.o \
		.objects/socamfsbusinesslogic.o \
		.objects/socamfsapplet.o \
		.objects/socamfswidget.o \
		.objects/moc_logowidget.o \
		.objects/moc_socamfsbusinesslogic.o \
		.objects/moc_socamfsapplet.o \
		.objects/moc_socamfswidget.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qmsystem2.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/timed.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/dcpconfig.pri \
		/usr/share/qt4/mkspecs/features/duicontrolpanel.prf \
		/usr/share/qt4/mkspecs/features/mobility.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_defines.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_common.prf \
		/usr/share/qt4/mkspecs/features/meegotouchcore.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		meegotouchcp-socamfs.pro
QMAKE_TARGET  = meegotouchcp-socamfs
DESTDIR       = lib/
TARGET        = libmeegotouchcp-socamfs.so
TARGETD       = libmeegotouchcp-socamfs.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  lib/$(TARGET)

lib/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) lib/



Makefile: meegotouchcp-socamfs.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qmsystem2.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/timed.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/dcpconfig.pri \
		/usr/share/qt4/mkspecs/features/duicontrolpanel.prf \
		/usr/share/qt4/mkspecs/features/mobility.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_defines.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf \
		/usr/share/qt4/mkspecs/features/meegotouch_common.prf \
		/usr/share/qt4/mkspecs/features/meegotouchcore.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtSystemInfo.prl
	$(QMAKE) -o Makefile meegotouchcp-socamfs.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qmsystem2.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/timed.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/dcpconfig.pri:
/usr/share/qt4/mkspecs/features/duicontrolpanel.prf:
/usr/share/qt4/mkspecs/features/mobility.prf:
/usr/share/qt4/mkspecs/features/meegotouch_defines.prf:
/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf:
/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf:
/usr/share/qt4/mkspecs/features/meegotouch_common.prf:
/usr/share/qt4/mkspecs/features/meegotouchcore.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtSystemInfo.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile meegotouchcp-socamfs.pro

dist: 
	@$(CHK_DIR_EXISTS) .objects/meegotouchcp-socamfs1.0.0 || $(MKDIR) .objects/meegotouchcp-socamfs1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .objects/meegotouchcp-socamfs1.0.0/ && $(COPY_FILE) --parents src/debug.h src/dcpdisplay.h src/logowidget.h src/socamfsbusinesslogic.h src/socamfsapplet.h src/socamfswidget.h .objects/meegotouchcp-socamfs1.0.0/ && $(COPY_FILE) --parents src/debug.cpp src/logowidget.cpp src/socamfsbusinesslogic.cpp src/socamfsapplet.cpp src/socamfswidget.cpp .objects/meegotouchcp-socamfs1.0.0/ && (cd `dirname .objects/meegotouchcp-socamfs1.0.0` && $(TAR) meegotouchcp-socamfs1.0.0.tar meegotouchcp-socamfs1.0.0 && $(COMPRESS) meegotouchcp-socamfs1.0.0.tar) && $(MOVE) `dirname .objects/meegotouchcp-socamfs1.0.0`/meegotouchcp-socamfs1.0.0.tar.gz . && $(DEL_FILE) -r .objects/meegotouchcp-socamfs1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_logowidget.cpp .moc/moc_socamfsbusinesslogic.cpp .moc/moc_socamfsapplet.cpp .moc/moc_socamfswidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_logowidget.cpp .moc/moc_socamfsbusinesslogic.cpp .moc/moc_socamfsapplet.cpp .moc/moc_socamfswidget.cpp
.moc/moc_logowidget.cpp: /usr/include/meegotouch/MImageWidget \
		/usr/include/meegotouch/mimagewidget.h \
		/usr/include/meegotouch/mwidgetcontroller.h \
		/usr/include/meegotouch/mwidget.h \
		/usr/include/meegotouch/mexport.h \
		/usr/include/meegotouch/mwindow.h \
		/usr/include/meegotouch/mnamespace.h \
		/usr/include/meegotouch/mtheme.h \
		/usr/include/meegotouch/mimagewidgetmodel.h \
		/usr/include/meegotouch/mwidgetmodel.h \
		/usr/include/meegotouch/MBanner \
		/usr/include/meegotouch/mbanner.h \
		/usr/include/meegotouch/mscenewindow.h \
		/usr/include/meegotouch/mscenewindowmodel.h \
		/usr/include/meegotouch/mbannermodel.h \
		src/logowidget.h
	mmoc.pl $(DEFINES) $(INCPATH) src/logowidget.h -o .moc/moc_logowidget.cpp

.moc/moc_socamfsbusinesslogic.cpp: /usr/include/qmsystem2/qmdisplaystate.h \
		/usr/include/qmsystem2/system_global.h \
		/usr/include/qmsystem2/qmdevicemode.h \
		src/socamfsbusinesslogic.h
	mmoc.pl $(DEFINES) $(INCPATH) src/socamfsbusinesslogic.h -o .moc/moc_socamfsbusinesslogic.cpp

.moc/moc_socamfsapplet.cpp: src/socamfswidget.h \
		/usr/include/duicontrolpanel/dcpwidget.h \
		/usr/include/meegotouch/MWidget \
		/usr/include/meegotouch/mwidget.h \
		/usr/include/meegotouch/mexport.h \
		/usr/include/meegotouch/mwindow.h \
		/usr/include/meegotouch/mnamespace.h \
		/usr/include/meegotouch/MTextEdit \
		/usr/include/meegotouch/mtextedit.h \
		/usr/include/meegotouch/mwidgetcontroller.h \
		/usr/include/meegotouch/mtheme.h \
		/usr/include/meegotouch/mtexteditmodel.h \
		/usr/include/meegotouch/mwidgetmodel.h \
		/usr/include/meegotouch/MLabel \
		/usr/include/meegotouch/mlabel.h \
		/usr/include/meegotouch/mlabelmodel.h \
		/usr/include/meegotouch/MBanner \
		/usr/include/meegotouch/mbanner.h \
		/usr/include/meegotouch/mscenewindow.h \
		/usr/include/meegotouch/mscenewindowmodel.h \
		/usr/include/meegotouch/mbannermodel.h \
		/usr/include/meegotouch/MInfoBanner \
		/usr/include/meegotouch/minfobanner.h \
		/usr/include/meegotouch/minfobannermodel.h \
		/usr/include/meegotouch/MSceneWindow \
		/usr/include/duicontrolpanel/dcpappletif.h \
		src/socamfsapplet.h
	mmoc.pl $(DEFINES) $(INCPATH) src/socamfsapplet.h -o .moc/moc_socamfsapplet.cpp

.moc/moc_socamfswidget.cpp: /usr/include/duicontrolpanel/dcpwidget.h \
		/usr/include/meegotouch/MWidget \
		/usr/include/meegotouch/mwidget.h \
		/usr/include/meegotouch/mexport.h \
		/usr/include/meegotouch/mwindow.h \
		/usr/include/meegotouch/mnamespace.h \
		/usr/include/meegotouch/MTextEdit \
		/usr/include/meegotouch/mtextedit.h \
		/usr/include/meegotouch/mwidgetcontroller.h \
		/usr/include/meegotouch/mtheme.h \
		/usr/include/meegotouch/mtexteditmodel.h \
		/usr/include/meegotouch/mwidgetmodel.h \
		/usr/include/meegotouch/MLabel \
		/usr/include/meegotouch/mlabel.h \
		/usr/include/meegotouch/mlabelmodel.h \
		/usr/include/meegotouch/MBanner \
		/usr/include/meegotouch/mbanner.h \
		/usr/include/meegotouch/mscenewindow.h \
		/usr/include/meegotouch/mscenewindowmodel.h \
		/usr/include/meegotouch/mbannermodel.h \
		/usr/include/meegotouch/MInfoBanner \
		/usr/include/meegotouch/minfobanner.h \
		/usr/include/meegotouch/minfobannermodel.h \
		/usr/include/meegotouch/MSceneWindow \
		src/socamfswidget.h
	mmoc.pl $(DEFINES) $(INCPATH) src/socamfswidget.h -o .moc/moc_socamfswidget.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_mgenerator_model_make_all:
compiler_mgenerator_model_clean:
	-$(DEL_FILE) ./gen_*
compiler_mgenerator_style_make_all:
compiler_mgenerator_style_clean:
	-$(DEL_FILE) ./gen_*
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.objects/debug.o: src/debug.cpp src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/debug.o src/debug.cpp

.objects/logowidget.o: src/logowidget.cpp src/logowidget.h \
		/usr/include/meegotouch/MImageWidget \
		/usr/include/meegotouch/mimagewidget.h \
		/usr/include/meegotouch/mwidgetcontroller.h \
		/usr/include/meegotouch/mwidget.h \
		/usr/include/meegotouch/mexport.h \
		/usr/include/meegotouch/mwindow.h \
		/usr/include/meegotouch/mnamespace.h \
		/usr/include/meegotouch/mtheme.h \
		/usr/include/meegotouch/mimagewidgetmodel.h \
		/usr/include/meegotouch/mwidgetmodel.h \
		/usr/include/meegotouch/MBanner \
		/usr/include/meegotouch/mbanner.h \
		/usr/include/meegotouch/mscenewindow.h \
		/usr/include/meegotouch/mscenewindowmodel.h \
		/usr/include/meegotouch/mbannermodel.h \
		src/debug.h \
		/usr/include/meegotouch/MGConfItem \
		/usr/include/meegotouch/mgconfitem.h \
		/usr/include/meegotouch/MWidgetCreator \
		/usr/include/meegotouch/mwidgetcreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/logowidget.o src/logowidget.cpp

.objects/socamfsbusinesslogic.o: src/socamfsbusinesslogic.cpp src/socamfsbusinesslogic.h \
		/usr/include/qmsystem2/qmdisplaystate.h \
		/usr/include/qmsystem2/system_global.h \
		/usr/include/qmsystem2/qmdevicemode.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/socamfsbusinesslogic.o src/socamfsbusinesslogic.cpp

.objects/socamfsapplet.o: src/socamfsapplet.cpp src/socamfsapplet.h \
		src/socamfswidget.h \
		/usr/include/duicontrolpanel/dcpwidget.h \
		/usr/include/meegotouch/MWidget \
		/usr/include/meegotouch/mwidget.h \
		/usr/include/meegotouch/mexport.h \
		/usr/include/meegotouch/mwindow.h \
		/usr/include/meegotouch/mnamespace.h \
		/usr/include/meegotouch/MTextEdit \
		/usr/include/meegotouch/mtextedit.h \
		/usr/include/meegotouch/mwidgetcontroller.h \
		/usr/include/meegotouch/mtheme.h \
		/usr/include/meegotouch/mtexteditmodel.h \
		/usr/include/meegotouch/mwidgetmodel.h \
		/usr/include/meegotouch/MLabel \
		/usr/include/meegotouch/mlabel.h \
		/usr/include/meegotouch/mlabelmodel.h \
		/usr/include/meegotouch/MBanner \
		/usr/include/meegotouch/mbanner.h \
		/usr/include/meegotouch/mscenewindow.h \
		/usr/include/meegotouch/mscenewindowmodel.h \
		/usr/include/meegotouch/mbannermodel.h \
		/usr/include/meegotouch/MInfoBanner \
		/usr/include/meegotouch/minfobanner.h \
		/usr/include/meegotouch/minfobannermodel.h \
		/usr/include/meegotouch/MSceneWindow \
		/usr/include/duicontrolpanel/dcpappletif.h \
		/usr/include/meegotouch/MAction \
		/usr/include/meegotouch/maction.h \
		/usr/include/meegotouch/MLibrary \
		/usr/include/meegotouch/mlibrary.h \
		/usr/include/meegotouch/massembly.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/socamfsapplet.o src/socamfsapplet.cpp

.objects/socamfswidget.o: src/socamfswidget.cpp src/socamfswidget.h \
		/usr/include/duicontrolpanel/dcpwidget.h \
		/usr/include/meegotouch/MWidget \
		/usr/include/meegotouch/mwidget.h \
		/usr/include/meegotouch/mexport.h \
		/usr/include/meegotouch/mwindow.h \
		/usr/include/meegotouch/mnamespace.h \
		/usr/include/meegotouch/MTextEdit \
		/usr/include/meegotouch/mtextedit.h \
		/usr/include/meegotouch/mwidgetcontroller.h \
		/usr/include/meegotouch/mtheme.h \
		/usr/include/meegotouch/mtexteditmodel.h \
		/usr/include/meegotouch/mwidgetmodel.h \
		/usr/include/meegotouch/MLabel \
		/usr/include/meegotouch/mlabel.h \
		/usr/include/meegotouch/mlabelmodel.h \
		/usr/include/meegotouch/MBanner \
		/usr/include/meegotouch/mbanner.h \
		/usr/include/meegotouch/mscenewindow.h \
		/usr/include/meegotouch/mscenewindowmodel.h \
		/usr/include/meegotouch/mbannermodel.h \
		/usr/include/meegotouch/MInfoBanner \
		/usr/include/meegotouch/minfobanner.h \
		/usr/include/meegotouch/minfobannermodel.h \
		/usr/include/meegotouch/MSceneWindow \
		src/socamfsbusinesslogic.h \
		/usr/include/qmsystem2/qmdisplaystate.h \
		/usr/include/qmsystem2/system_global.h \
		/usr/include/qmsystem2/qmdevicemode.h \
		src/styles.h \
		src/dcpdisplay.h \
		src/debug.h \
		/usr/include/meegotouch/MButton \
		/usr/include/meegotouch/mbutton.h \
		/usr/include/meegotouch/mbuttonmodel.h \
		/usr/include/meegotouch/MWidgetController \
		/usr/include/meegotouch/MComboBox \
		/usr/include/meegotouch/mcombobox.h \
		/usr/include/meegotouch/mcomboboxmodel.h \
		/usr/include/meegotouch/MLayout \
		/usr/include/meegotouch/mlayout.h \
		/usr/include/meegotouch/MSlider \
		/usr/include/meegotouch/mslider.h \
		/usr/include/meegotouch/mslidermodel.h \
		/usr/include/meegotouch/MLinearLayoutPolicy \
		/usr/include/meegotouch/mlinearlayoutpolicy.h \
		/usr/include/meegotouch/mabstractlayoutpolicy.h \
		/usr/include/meegotouch/MSeparator \
		/usr/include/meegotouch/mseparator.h \
		/usr/include/meegotouch/mseparatormodel.h \
		/usr/include/meegotouch/MHelpButton \
		/usr/include/meegotouch/mhelpbutton.h \
		/usr/include/meegotouch/MGConfItem \
		/usr/include/meegotouch/mgconfitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/socamfswidget.o src/socamfswidget.cpp

.objects/moc_logowidget.o: .moc/moc_logowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/moc_logowidget.o .moc/moc_logowidget.cpp

.objects/moc_socamfsbusinesslogic.o: .moc/moc_socamfsbusinesslogic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/moc_socamfsbusinesslogic.o .moc/moc_socamfsbusinesslogic.cpp

.objects/moc_socamfsapplet.o: .moc/moc_socamfsapplet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/moc_socamfsapplet.o .moc/moc_socamfsapplet.cpp

.objects/moc_socamfswidget.o: .moc/moc_socamfswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .objects/moc_socamfswidget.o .moc/moc_socamfswidget.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/duicontrolpanel/applets/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/duicontrolpanel/applets/ 
	-$(INSTALL_PROGRAM) "lib/$(TARGET)" "$(INSTALL_ROOT)/usr/lib/duicontrolpanel/applets/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/usr/lib/duicontrolpanel/applets/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/duicontrolpanel/applets/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/duicontrolpanel/applets/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

