# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       meegotouchcp-socamfs

# >> macros
# << macros

Summary:    SocamFS configuration applet
Version:    1.0.0
Release:    1
Group:      Applications/System
License:    TBD
Source0:    %{name}-%{version}.tar.bz2
Requires:  pkgconfig(QtCore) >= 4.7.0
#Requires:  pkgconfig(QtGui)
#Requires:  pkgconfig(QtWebKit)
#Requires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtWebKit)
BuildRequires:  pkgconfig(QtOpenGL)
Provides:   meegotouchcp-socamfs = 1.0.0

%description
SocamFS configuration applet

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

qmake meegotouchcp-socamfs.pro

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
make install INSTALL_ROOT=%{buildroot}

# >> install post
# << install post

%post
# >> post

# << post

%files
%defattr(-,root,root,-)
/usr/lib/duicontrolpanel/applets/libmeegotouchcp-socamfs.so

# >> files
# << files
